name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        id: trufflehog
        uses: trufflesecurity/trufflehog@main
        continue-on-error: true
        with:
          path: ./
          extra_args: --debug
          # For PRs: scan only the PR diff range
          base: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.before }}
          head: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}

      - name: Scan Results Status
        if: steps.trufflehog.outcome == 'failure'
        run: exit 1
  
  Lint: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26'
      
      - name: Lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.11
  
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26'
        
      - name: Run go tests
        run: make test

  Integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26'
      
      - name: Run integration tests
        run: make ci


